services:
  app:
    build: .
    container_name: task-scheduler-app
    ports:
      - "50053:50053"
      - "2113:2113"
    depends_on:
      - redis
    environment:
      - REDIS_ADDR=redis:6379
      - METRICS_PORT=2113
      - AUTH_TOKEN=my-secret-token
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: task-scheduler-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    depends_on:
      - app

volumes:
  redis_data:
    driver: local